// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8doWRx-GFLpienN2JHCY7jDQ2TTt7Elo',
    appId: '1:801724453027:web:1bd19ccacd3e1f58da2f16',
    messagingSenderId: '801724453027',
    projectId: 'blogg-app-e7ed8',
    authDomain: 'blogg-app-e7ed8.firebaseapp.com',
    storageBucket: 'blogg-app-e7ed8.firebasestorage.app',
    measurementId: 'G-NK6KB3E5LH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvaOkzakeeVlfRiz5_95zmAs6WO5FZLYI',
    appId: '1:801724453027:android:3c0f2ff40cfd867cda2f16',
    messagingSenderId: '801724453027',
    projectId: 'blogg-app-e7ed8',
    storageBucket: 'blogg-app-e7ed8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAApQUx7BAL5Jjh_JtBggUOOpsLD41Nu34',
    appId: '1:801724453027:ios:be9cfba3fd8ce626da2f16',
    messagingSenderId: '801724453027',
    projectId: 'blogg-app-e7ed8',
    storageBucket: 'blogg-app-e7ed8.firebasestorage.app',
    iosBundleId: 'com.example.bloggApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAApQUx7BAL5Jjh_JtBggUOOpsLD41Nu34',
    appId: '1:801724453027:ios:be9cfba3fd8ce626da2f16',
    messagingSenderId: '801724453027',
    projectId: 'blogg-app-e7ed8',
    storageBucket: 'blogg-app-e7ed8.firebasestorage.app',
    iosBundleId: 'com.example.bloggApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8doWRx-GFLpienN2JHCY7jDQ2TTt7Elo',
    appId: '1:801724453027:web:063439d5ad8678f1da2f16',
    messagingSenderId: '801724453027',
    projectId: 'blogg-app-e7ed8',
    authDomain: 'blogg-app-e7ed8.firebaseapp.com',
    storageBucket: 'blogg-app-e7ed8.firebasestorage.app',
    measurementId: 'G-HXJYSKSEY7',
  );
}
